name: Build and Deploy Docs

on:
  # Keep manual until you're ready to go public.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mirror policies into docs
        run: bash scripts/sync_policies.sh

      - name: Redact PRIVATE blocks
        run: |
          python scripts/redact.py $(git ls-files '*.md' '*.txt')

      - name: Deploy
        run: |
          mkdocs gh-deploy --force
