name: Corpus Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run corpus script
        run: |
          python starter/scripts/corpus.py | tee corpus.log

      - name: Summary
        if: always()
        run: |
          echo "## Corpus Check" >> $GITHUB_STEP_SUMMARY
          grep -E '^(Contributions|Income|Expenses|Deployments|Corpus|Meets)' corpus.log >> $GITHUB_STEP_SUMMARY
